# Generated by Django 3.2.5 on 2023-04-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatoReparto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_cita', models.DateTimeField(verbose_name='CITA')),
                ('cp', models.PositiveBigIntegerField(verbose_name='CÓDIGO POSTAL')),
                ('direccion', models.CharField(max_length=200, verbose_name='DIRECCIÓN')),
                ('nhc', models.CharField(max_length=10, verbose_name='NHC')),
                ('movil', models.PositiveBigIntegerField(verbose_name='MÓVIL')),
                ('agenda', models.CharField(blank=True, max_length=30, null=True, verbose_name='AGENDA')),
                ('estado', models.CharField(blank=True, max_length=100, null=True, verbose_name='ESTADO')),
                ('DNI', models.CharField(blank=True, max_length=9, null=True, verbose_name='DNI')),
                ('incidencias', models.CharField(blank=True, max_length=200, null=True, verbose_name='INCIDENCIAS')),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
