# Generated by Django 3.2.5 on 2023-05-05 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FARMAHOME', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datoreparto',
            options={'permissions': (('can_download_data', 'Can download data.'),)},
        ),
    ]
