# Generated by Django 3.2.5 on 2023-05-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FARMAHOME', '0003_alter_datoreparto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='datoreparto',
            name='usuario_registro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='USUARIO'),
        ),
    ]
