# Generated by Django 3.2.5 on 2023-05-08 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FARMAHOME', '0005_rename_dia_cita_datoreparto_fecha_cita'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datoreparto',
            old_name='agenda',
            new_name='agenda_cita',
        ),
        migrations.RenameField(
            model_name='datoreparto',
            old_name='cp',
            new_name='codigo_postal',
        ),
        migrations.RenameField(
            model_name='datoreparto',
            old_name='estado',
            new_name='estado_entrega',
        ),
    ]
