# Generated by Django 3.2.5 on 2023-05-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FARMAHOME', '0007_alter_datoreparto_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=150, verbose_name='USUARIO')),
                ('fecha_inicio', models.DateTimeField(verbose_name='FECHA_INICIO')),
                ('fecha_fin', models.DateTimeField(null=True, verbose_name='FECHA_FIN')),
            ],
            options={
                'permissions': (('can_register_route', 'Can register route.'),),
            },
        ),
        migrations.AlterModelOptions(
            name='datoreparto',
            options={'permissions': (('can_download_data', 'Can download data.'), ('can_upload_data', 'Can upload data.'), ('can_register_data', 'Can register data.'))},
        ),
    ]
